BOT_TOKEN: 
  - MTM1OTUzMTY2NTk2NTMyMjQ5Mw.GaGv_C.4mOGYJDgC3vbtgzJXdr7RcaiqWfGBvqmkvPZVg
CHANNEL_ID: 
  - 1555300005445636256
MODE: custom
REPLY:
SIMSIMI_LANG: en
DELAY: [13,18]
DEL_AFTER:
REPOST_LAST_CHAT: